
services:
  app:
    build:
      context: ..
      dockerfile: container/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ..:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18
    container_name: sistema_educacional-postgres
    restart: always
    env_file:
      - postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql
      - ../patch:/docker-entrypoint-initdb.d/patch:ro
      - ./init-db.sql:/docker-entrypoint-initdb.d/00-init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      timeout: 5s
      interval: 10s
      retries: 5

volumes:
  postgres_data:
  node_modules: