CREATE TABLE IF NOT EXISTS `eventos_calendario` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`titulo` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`tipo` VARCHAR(20) NOT NULL DEFAULT 'evento' COLLATE 'utf8mb4_0900_ai_ci',
	`data_inicio` DATE NOT NULL,
	`data_fim` DATE NULL DEFAULT NULL,
	`descricao` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`excluido` INT NOT NULL DEFAULT '0',
	`criado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`atualizado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;
