CREATE TABLE IF NOT EXISTS `configuracao_notas` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`tipo` VARCHAR(20) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`nota_minima` DECIMAL(5,2) NOT NULL,
	`recuperacao` TINYINT(1) NOT NULL,
	`nota_recuperacao` DECIMAL(5,2) NOT NULL,
	`criado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`atualizado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	`excluido` INT NOT NULL DEFAULT '0',
	`nota_maxima` DECIMAL(5,2) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
);