CREATE TABLE params_disciplina (
    id INT AUTO_INCREMENT,
    text VARCHAR(20) NOT NULL,
    sigla VARCHAR(10) NOT NULL,
    carga_horaria INT NOT NULL,
    idStatus INT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
