CREATE TABLE `params_disciplina` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`text` VARCHAR(20) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`sigla` VARCHAR(10) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`carga_horaria` INT NOT NULL,
	`idStatus` INT NOT NULL DEFAULT '1',
	`criado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`atualizado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	`excluido` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;
