CREATE TABLE params_cargos (
    id INT AUTO_INCREMENT,
    text VARCHAR(20) NOT NULL,
    excluido INT DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    excluido INT  NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);