-- ============================================================
-- PATCH GERAL
-- Sistema Educacional
-- PostgreSQL
-- ============================================================

-- ============================================================
-- ALUNOS
-- ============================================================

CREATE TABLE IF NOT EXISTS alunos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    nome_social VARCHAR(255),
    cpf VARCHAR(14),
    rg VARCHAR(20),
    matricula VARCHAR(20),
    data_nascimento DATE,
    sexo CHAR(1),
    nacionalidade VARCHAR(100),
    naturalidade VARCHAR(100),
    id_estado_nascimento INT,
    foto BYTEA,
    id_tipo_documento INT,
    numero_documento VARCHAR(50),
    orgao_expedidor VARCHAR(50),
    data_expedicao DATE,
    certidao_nascimento VARCHAR(50),
    numero_certidao VARCHAR(50),
    observacoes TEXT,
    id_status INT,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_alunos_id_estado_nascimento
    ON alunos (id_estado_nascimento);

CREATE INDEX IF NOT EXISTS idx_alunos_id_tipo_documento
    ON alunos (id_tipo_documento);


-- ============================================================
-- EVENTOS DO CALENDÁRIO
-- ============================================================

CREATE TABLE IF NOT EXISTS eventos_calendario (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'evento',
    data_inicio DATE NOT NULL,
    data_fim DATE,
    descricao TEXT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- ============================================================
-- CONFIGURAÇÃO DE NOTAS
-- ============================================================

CREATE TABLE IF NOT EXISTS configuracao_notas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR(20) NOT NULL,
    nota_minima DECIMAL(5,2) NOT NULL,
    recuperacao SMALLINT NOT NULL,
    nota_recuperacao DECIMAL(5,2) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    nota_maxima DECIMAL(5,2),
    PRIMARY KEY (id)
);


-- ============================================================
-- ANOS LETIVOS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_anos_letivos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    ano_letivo INT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    atual SMALLINT NOT NULL DEFAULT 0,
    text TEXT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- ============================================================
-- PERÍODOS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_periodos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    abreviacao VARCHAR(20),
    ano_letivo VARCHAR(20),
    data_inicio DATE,
    data_fim DATE,
    ordem INT,
    tipo VARCHAR(30),
    status SMALLINT NOT NULL DEFAULT 1,
    text TEXT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- ============================================================
-- TURNOS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_turnos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(20),
    horario_inicio TIME,
    horario_final TIME,
    status SMALLINT NOT NULL DEFAULT 1,
    text TEXT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- ============================================================
-- SALAS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_salas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    codigo VARCHAR(20),
    tipo VARCHAR(50),
    capacidade INT,
    bloco VARCHAR(20),
    andar VARCHAR(20),
    recursos VARCHAR(255),
    status SMALLINT NOT NULL DEFAULT 1,
    text TEXT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- ============================================================
-- TIPOS DE AVALIAÇÃO
-- ============================================================

CREATE TABLE IF NOT EXISTS params_tipos_avaliacao (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(20),
    nota_maxima DECIMAL(5,2),
    status SMALLINT NOT NULL DEFAULT 1,
    text TEXT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- ============================================================
-- CONFIGURAÇÕES DA ESCOLA
-- ============================================================

CREATE TABLE IF NOT EXISTS configuracoes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL,
    logo VARCHAR(255),
    telefone VARCHAR(20) NOT NULL,
    whatsapp VARCHAR(20),
    email VARCHAR(255) NOT NULL,
    site VARCHAR(255),
    ano_letivo_atual INT NOT NULL,
    horario_funcionamento VARCHAR(50) NOT NULL,
    fuso_horario VARCHAR(50) NOT NULL,
    moeda VARCHAR(10) NOT NULL,
    cep VARCHAR(10) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(255),
    bairro VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    idEstado INT,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    tema_sistema VARCHAR(50) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (email)
);


-- ============================================================
-- DISCIPLINAS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_disciplina (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(255) NOT NULL,
    sigla VARCHAR(10) NOT NULL,
    descricao TEXT,
    carga_horaria INT NOT NULL,
    idStatus INT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);


-- ============================================================
-- DOCUMENTOS
-- ============================================================

CREATE TABLE IF NOT EXISTS documentos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    idTipo INT,
    descricao TEXT,
    arquivo VARCHAR(255),
    data_documento DATE,
    data_validade DATE,
    idStatus INT DEFAULT 1,
    publico INT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_documentos_idTipo
    ON documentos (idTipo);


-- ============================================================
-- ESTADOS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_estados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(255) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_params_estados_uf
    ON params_estados (uf);


-- ============================================================
-- FORMAÇÃO
-- ============================================================

CREATE TABLE IF NOT EXISTS params_formacao (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(255) NOT NULL,
    idStatus INT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);


-- ============================================================
-- NOTIFICAÇÕES
-- ============================================================

CREATE TABLE IF NOT EXISTS notificacoes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'evento',
    prioridade VARCHAR(20) NOT NULL DEFAULT 'normal',
    mensagem TEXT,
    destinatarios TEXT,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    enviar_notificacao INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);


-- ============================================================
-- CARGOS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_cargos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);


-- ============================================================
-- STATUS DE DOCUMENTOS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_status_documentos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(20) NOT NULL,
    cor VARCHAR(7) NOT NULL DEFAULT '#000000',
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);


-- ============================================================
-- ROLES
-- ============================================================

CREATE TABLE IF NOT EXISTS roles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (name)
);


-- ============================================================
-- PERMISSÕES
-- ============================================================

CREATE TABLE IF NOT EXISTS permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (name)
);


-- ============================================================
-- ROLE x PERMISSIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS role_permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    access VARCHAR(10) NOT NULL DEFAULT 'none',
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),

    CONSTRAINT role_permissions_fk_role
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
        ON DELETE CASCADE,

    CONSTRAINT role_permissions_fk_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions (id)
        ON DELETE CASCADE,

    UNIQUE (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id
    ON role_permissions (permission_id);


-- ============================================================
-- PROFESSORES
-- ============================================================

CREATE TABLE IF NOT EXISTS professores (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    nome_social VARCHAR(255),
    cpf VARCHAR(20),
    data_nascimento DATE,
    sexo VARCHAR(1),
    id_disciplina INT,
    carga_horaria VARCHAR(20),
    id_status SMALLINT NOT NULL DEFAULT 1,
    email VARCHAR(255),
    telefone VARCHAR(20),
    celular VARCHAR(20),
    cep VARCHAR(15),
    endereco VARCHAR(255),
    numeros VARCHAR(20),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    id_estado INT,
    matricula VARCHAR(50),
    registro_profissional VARCHAR(50),
    data_admissao DATE,
    formacao VARCHAR(255),
    area_formacao VARCHAR(255),
    observacoes TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),

    CONSTRAINT fk_professores_disciplina
        FOREIGN KEY (id_disciplina)
        REFERENCES params_disciplina(id),

    CONSTRAINT fk_professores_estado
        FOREIGN KEY (id_estado)
        REFERENCES params_estados(id)
);


-- ============================================================
-- SÉRIES
-- ============================================================

CREATE TABLE IF NOT EXISTS params_series (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    abreviacao VARCHAR(20),
    etapa_ensino VARCHAR(50),
    nivel_ensino VARCHAR(50),
    ano_serie INT,
    codigo VARCHAR(20),
    idTurnos INT,
    idade_minima INT,
    idade_maxima INT,
    carga_horaria INT,
    aulas_semanais INT,
    status SMALLINT NOT NULL DEFAULT 1,
    descricao TEXT,
    excluido INT NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),

    CONSTRAINT fk_params_series_params_turnos
        FOREIGN KEY (idTurnos)
        REFERENCES params_turnos (id)
);

CREATE INDEX IF NOT EXISTS idx_params_series_idTurnos
    ON params_series (idTurnos);


-- ============================================================
-- APARÊNCIA DO SISTEMA
-- Mantido o nome original "sistema_aparecia"
-- para não quebrar referências existentes.
-- ============================================================

CREATE TABLE IF NOT EXISTS sistema_aparecia (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    tema_sistema VARCHAR(20) NOT NULL,
    cor_principal VARCHAR(20) NOT NULL,
    menu_lateral VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);


-- ============================================================
-- TIPOS DE DOCUMENTOS
-- ============================================================

CREATE TABLE IF NOT EXISTS params_tipos_documentos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_params_tipos_documentos_text
    ON params_tipos_documentos (text);


CREATE TABLE IF NOT EXISTS params_tipos_usuarios (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    descricao VARCHAR(100) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    excluido INTEGER NOT NULL DEFAULT 0
);

-- ============================================================
-- FK DOCUMENTOS -> TIPOS DE DOCUMENTOS
-- PostgreSQL não permite ADD CONSTRAINT IF NOT EXISTS.
-- Por isso usamos DO $$.
-- ============================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_documentos_params_tipos_documentos'
    ) THEN
        ALTER TABLE documentos
            ADD CONSTRAINT fk_documentos_params_tipos_documentos
            FOREIGN KEY (idTipo)
            REFERENCES params_tipos_documentos (id);
    END IF;
END
$$;

INSERT INTO params_tipos_usuarios (codigo, descricao)
VALUES
    ('ADMIN', 'Administradores'),
    ('PROFESSOR', 'Professores'),
    ('ALUNO', 'Alunos'),
    ('ALL', 'ALL')
ON CONFLICT (codigo) DO UPDATE
SET descricao = EXCLUDED.descricao,
atualizado_em = CURRENT_TIMESTAMP;

-- ============================================================
-- USUÁRIOS
-- ============================================================

CREATE TABLE "usuarios" (
	"id" INTEGER NOT NULL,
	"telefone" VARCHAR(20) NOT NULL,
	"nome" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"idcargo" INTEGER NULL DEFAULT NULL,
	"data_nascimento" DATE NULL DEFAULT NULL,
	"excluido" INTEGER NOT NULL DEFAULT 0,
	"criado_em" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"senha" VARCHAR(255) NOT NULL,
	"avatar" VARCHAR(255) NULL DEFAULT NULL,
	"termos" INTEGER NOT NULL DEFAULT 0,
	"atualizado_em" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	"id_aluno" INTEGER NULL DEFAULT NULL,
	"id_professor" INTEGER NULL DEFAULT NULL,
	"id_tipo_usuario" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("id"),
	UNIQUE ("email"),
	CONSTRAINT "FK_usuarios_params_tipos_usuarios" FOREIGN KEY ("id_tipo_usuario") REFERENCES "params_tipos_usuarios" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
)
;
COMMENT ON COLUMN "usuarios"."id" IS '';
COMMENT ON COLUMN "usuarios"."telefone" IS '';
COMMENT ON COLUMN "usuarios"."nome" IS '';
COMMENT ON COLUMN "usuarios"."email" IS '';
COMMENT ON COLUMN "usuarios"."idcargo" IS '';
COMMENT ON COLUMN "usuarios"."data_nascimento" IS '';
COMMENT ON COLUMN "usuarios"."excluido" IS '';
COMMENT ON COLUMN "usuarios"."criado_em" IS '';
COMMENT ON COLUMN "usuarios"."senha" IS '';
COMMENT ON COLUMN "usuarios"."avatar" IS '';
COMMENT ON COLUMN "usuarios"."termos" IS '';
COMMENT ON COLUMN "usuarios"."atualizado_em" IS '';
COMMENT ON COLUMN "usuarios"."id_aluno" IS '';
COMMENT ON COLUMN "usuarios"."id_professor" IS '';
COMMENT ON COLUMN "usuarios"."id_tipo_usuario" IS '';
CREATE INDEX "idx_usuarios_id_aluno" ON "usuarios" ("id_aluno");
CREATE INDEX "idx_usuarios_id_professor" ON "usuarios" ("id_professor");
CREATE INDEX "idx_usuarios_tipo_usuario" ON "usuarios" ("id_tipo_usuario");



-- ============================================================
-- USUÁRIOS PERMISSÕES
-- ============================================================

CREATE TABLE IF NOT EXISTS usuariosPermissoes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(20) NOT NULL,
    idCargo INT NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);





-- ============================================================
-- SEED: ESTADOS
-- ============================================================

INSERT INTO params_estados (uf, text)
VALUES
('AC', 'Acre'),
('AL', 'Alagoas'),
('AP', 'Amapá'),
('AM', 'Amazonas'),
('BA', 'Bahia'),
('CE', 'Ceará'),
('DF', 'Distrito Federal'),
('ES', 'Espírito Santo'),
('GO', 'Goiás'),
('MA', 'Maranhão'),
('MT', 'Mato Grosso'),
('MS', 'Mato Grosso do Sul'),
('MG', 'Minas Gerais'),
('PA', 'Pará'),
('PB', 'Paraíba'),
('PR', 'Paraná'),
('PE', 'Pernambuco'),
('PI', 'Piauí'),
('RJ', 'Rio de Janeiro'),
('RN', 'Rio Grande do Norte'),
('RS', 'Rio Grande do Sul'),
('RO', 'Rondônia'),
('RR', 'Roraima'),
('SC', 'Santa Catarina'),
('SP', 'São Paulo'),
('SE', 'Sergipe'),
('TO', 'Tocantins')
ON CONFLICT (uf) DO NOTHING;


-- ============================================================
-- SEED: FORMAÇÕES
-- ============================================================

INSERT INTO params_formacao (text, idStatus)
SELECT v.text, 1
FROM (
    VALUES
        ('Ensino Médio'),
        ('Técnico'),
        ('Licenciatura'),
        ('Bacharelado'),
        ('Tecnólogo'),
        ('Pós-graduação'),
        ('Especialização'),
        ('Mestrado'),
        ('Doutorado'),
        ('Pós-doutorado'),
        ('Outro')
) AS v(text)
WHERE NOT EXISTS (
    SELECT 1
    FROM params_formacao pf
    WHERE pf.text = v.text
);


-- ============================================================
-- SEED: ROLES
-- ============================================================

INSERT INTO roles (name)
VALUES
('Administradores'),
('Professores'),
('Alunos'),
('Responsáveis'),
('Secretaria'),
('Coordenação')
ON CONFLICT (name) DO NOTHING;


-- ============================================================
-- SEED: PERMISSÕES
-- ============================================================

INSERT INTO permissions (name)
VALUES
('Ver alunos'),
('Criar alunos'),
('Notas'),
('Frequência'),
('Financeiro'),
('Configurações')
ON CONFLICT (name) DO NOTHING;


-- ============================================================
-- SEED: ROLE PERMISSIONS
-- ============================================================

-- Administradores: acesso total
INSERT INTO role_permissions (
    role_id,
    permission_id,
    access
)
SELECT
    r.id,
    p.id,
    'full'
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'Administradores'
ON CONFLICT (role_id, permission_id)
DO UPDATE SET
    access = EXCLUDED.access;


-- Professores: alunos, notas e frequência
INSERT INTO role_permissions (
    role_id,
    permission_id,
    access
)
SELECT
    r.id,
    p.id,
    'full'
FROM roles r
JOIN permissions p
    ON p.name IN (
        'Ver alunos',
        'Notas',
        'Frequência'
    )
WHERE r.name = 'Professores'
ON CONFLICT (role_id, permission_id)
DO UPDATE SET
    access = EXCLUDED.access;


-- Alunos: notas e frequência somente visualização
INSERT INTO role_permissions (
    role_id,
    permission_id,
    access
)
SELECT
    r.id,
    p.id,
    'view'
FROM roles r
JOIN permissions p
    ON p.name IN (
        'Notas',
        'Frequência'
    )
WHERE r.name = 'Alunos'
ON CONFLICT (role_id, permission_id)
DO UPDATE SET
    access = EXCLUDED.access;


-- ============================================================
-- SEED: TIPOS DE DOCUMENTOS
-- ============================================================

INSERT INTO params_tipos_documentos (text)
SELECT v.text
FROM (
    VALUES
        ('Regimento escolar'),
        ('Projeto político-pedagógico'),
        ('Calendário escolar'),
        ('Plano de ensino'),
        ('Plano de aula'),
        ('Ata'),
        ('Declaração'),
        ('Histórico escolar'),
        ('Boletim'),
        ('Ficha de matrícula'),
        ('Contrato'),
        ('Comunicado'),
        ('Ofício'),
        ('Circular'),
        ('Histórico Escolar'),
        ('Outro')
) AS v(text)
WHERE NOT EXISTS (
    SELECT 1
    FROM params_tipos_documentos p
    WHERE p.text = v.text
);


-- ============================================================
-- SEED: DISCIPLINAS
-- ============================================================

INSERT INTO params_disciplina (
    text,
    descricao,
    sigla,
    carga_horaria,
    idStatus
)
SELECT
    v.text,
    v.descricao,
    v.sigla,
    v.carga_horaria,
    1
FROM (
    VALUES
        (
            'Língua Portuguesa',
            'Componente curricular de Língua Portuguesa',
            'LP',
            200
        ),
        (
            'Matemática',
            'Componente curricular de Matemática',
            'MAT',
            200
        ),
        (
            'Ciências',
            'Componente curricular de Ciências da Natureza no Ensino Fundamental',
            'CIE',
            120
        ),
        (
            'História',
            'Componente curricular de História',
            'HIS',
            120
        ),
        (
            'Geografia',
            'Componente curricular de Geografia',
            'GEO',
            120
        ),
        (
            'Arte',
            'Componente curricular de Arte',
            'ART',
            80
        ),
        (
            'Educação Física',
            'Componente curricular de Educação Física',
            'EF',
            80
        ),
        (
            'Língua Inglesa',
            'Componente curricular de Língua Inglesa',
            'ING',
            120
        ),
        (
            'Ensino Religioso',
            'Componente curricular de Ensino Religioso',
            'ER',
            40
        ),
        (
            'Biologia',
            'Componente curricular de Biologia do Ensino Médio',
            'BIO',
            120
        ),
        (
            'Física',
            'Componente curricular de Física do Ensino Médio',
            'FIS',
            120
        ),
        (
            'Química',
            'Componente curricular de Química do Ensino Médio',
            'QUI',
            120
        ),
        (
            'Filosofia',
            'Componente curricular de Filosofia do Ensino Médio',
            'FIL',
            80
        ),
        (
            'Sociologia',
            'Componente curricular de Sociologia do Ensino Médio',
            'SOC',
            80
        ),
        (
            'Língua Espanhola',
            'Língua estrangeira adicional, conforme oferta da rede',
            'ESP',
            80
        ),
        (
            'Projeto de Vida',
            'Componente destinado ao desenvolvimento pessoal, social e profissional',
            'PV',
            80
        ),
        (
            'Tecnologia e Inovação',
            'Tecnologia, cultura digital e inovação',
            'TI',
            80
        ),
        (
            'Educação Financeira',
            'Educação financeira e planejamento financeiro',
            'EFI',
            40
        ),
        (
            'Robótica',
            'Robótica educacional e pensamento computacional',
            'ROB',
            80
        ),
        (
            'Programação',
            'Programação e pensamento computacional',
            'PRO',
            80
        ),
        (
            'Empreendedorismo',
            'Empreendedorismo e desenvolvimento de projetos',
            'EMP',
            40
        ),
        (
            'Orientação de Estudos',
            'Acompanhamento e desenvolvimento de estratégias de estudo',
            'OE',
            80
        ),
        (
            'Eletiva',
            'Componente curricular eletivo definido pela unidade ou rede de ensino',
            'ELE',
            40
        )
) AS v(
    text,
    descricao,
    sigla,
    carga_horaria
)
WHERE NOT EXISTS (
    SELECT 1
    FROM params_disciplina p
    WHERE p.sigla = v.sigla
);


-- ============================================================
-- FIM DO PATCH
-- ============================================================