-- Tabela de papéis
CREATE TABLE IF NOT EXISTS roles (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	excluido INT NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS permissions (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100) NOT NULL,
	excluido INT NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	UNIQUE (name)
);



-- Matriz que liga papéis a permissões com nível de acesso
CREATE TABLE IF NOT EXISTS role_permissions (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	role_id INT NOT NULL,
	permission_id INT NOT NULL,
	access VARCHAR(10) NOT NULL DEFAULT 'none',
	excluido INT NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	UNIQUE (role_id, permission_id),
	CONSTRAINT role_permissions_fk_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
	CONSTRAINT role_permissions_fk_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON role_permissions (permission_id);


-- Inserir papéis básicos
INSERT INTO roles (name) VALUES
('Administradores'),
('Professores'),
('Alunos'),
('Responsáveis'),
('Secretaria'),
('Coordenação')
ON CONFLICT (name) DO NOTHING;

-- Inserir permissões básicas
INSERT INTO permissions (name) VALUES
('Ver alunos'),
('Criar alunos'),
('Notas'),
('Frequência'),
('Financeiro'),
('Configurações')
ON CONFLICT (name) DO NOTHING;

-- Exemplo de povoamento inicial: administradores full
INSERT INTO role_permissions (role_id, permission_id, access)
SELECT r.id, p.id, 'full'
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'Administradores'
ON CONFLICT (role_id, permission_id) DO UPDATE SET access = EXCLUDED.access;

-- Professores: ver, notas e frequência full
INSERT INTO role_permissions (role_id, permission_id, access)
SELECT r.id, p.id, 'full'
FROM roles r
JOIN permissions p ON p.name IN ('Ver alunos','Notas','Frequência')
WHERE r.name = 'Professores'
ON CONFLICT (role_id, permission_id) DO UPDATE SET access = EXCLUDED.access;

-- Alunos: notas e frequência como view
INSERT INTO role_permissions (role_id, permission_id, access)
SELECT r.id, p.id, 'view'
FROM roles r
JOIN permissions p ON p.name IN ('Notas','Frequência')
WHERE r.name = 'Alunos'
ON CONFLICT (role_id, permission_id) DO UPDATE SET access = EXCLUDED.access;
