CREATE TABLE professores (
    id INT AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    nome_social VARCHAR(255),
    cpf VARCHAR(20),
    data_nascimento DATE,
    sexo VARCHAR(1),
    id_disciplina INT,
    carga_horaria VARCHAR(20),
    id_status TINYINT(1) NOT NULL DEFAULT 1,
    email VARCHAR(255),
    telefone VARCHAR(20),
    celular VARCHAR(20),
    cep VARCHAR(15),
    endereco VARCHAR(255),
    numeros VARCHAR(20),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    id_estado INT,
    matricula VARCHAR(50),
    registro_profissional VARCHAR(50),
    data_admissao DATE,
    formacao VARCHAR(255),
    area_formacao VARCHAR(255),
    observacoes TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_professores_disciplina FOREIGN KEY (id_disciplina) REFERENCES params_disciplina(id),
    CONSTRAINT fk_professores_estado FOREIGN KEY (id_estado) REFERENCES params_estados(id)
);
