CREATE TABLE IF NOT EXISTS `sistema_aparecia` (
    id INT NOT NULL AUTO_INCREMENT,
    tema_sistema VARCHAR(20) NOT NULL,
    cor_principal VARCHAR(20) NOT NULL,
    menu_lateral VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
