CREATE TABLE IF NOT EXISTS turma_alunos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_turma INT NOT NULL,
    id_aluno INT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    excluido SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (id_turma, id_aluno),
    CONSTRAINT fk_turma_alunos_turma FOREIGN KEY (id_turma) REFERENCES turmas(id),
    CONSTRAINT fk_turma_alunos_aluno FOREIGN KEY (id_aluno) REFERENCES alunos(id)
);

CREATE INDEX IF NOT EXISTS idx_turma_alunos_aluno ON turma_alunos (id_aluno);

CREATE TABLE IF NOT EXISTS turma_professores (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_turma INT NOT NULL,
    id_professor INT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    excluido SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (id_turma, id_professor),
    CONSTRAINT fk_turma_professores_turma FOREIGN KEY (id_turma) REFERENCES turmas(id),
    CONSTRAINT fk_turma_professores_professor FOREIGN KEY (id_professor) REFERENCES professores(id)
);

CREATE INDEX IF NOT EXISTS idx_turma_professores_professor ON turma_professores (id_professor);