CREATE TABLE IF NOT EXISTS turmas (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	text VARCHAR(255) NOT NULL,
	sigla VARCHAR(20),
	id_ano_letivo INT,
	id_serie INT,
	id_turno INT,
	id_salas INT,
	id_status INT,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	excluido INT DEFAULT 0,
	PRIMARY KEY (id),
	CONSTRAINT fk_params_turmas_params_ano_letivo FOREIGN KEY (id_ano_letivo) REFERENCES params_anos_letivos (id),
	CONSTRAINT fk_params_turmas_params_salas FOREIGN KEY (id_salas) REFERENCES params_salas (id),
	CONSTRAINT fk_params_turmas_params_serie FOREIGN KEY (id_serie) REFERENCES params_series (id),
	CONSTRAINT fk_params_turmas_params_turnos FOREIGN KEY (id_turno) REFERENCES params_turnos (id)
);

CREATE INDEX IF NOT EXISTS idx_turmas_id_turno ON turmas (id_turno);
CREATE INDEX IF NOT EXISTS idx_turmas_id_ano_letivo ON turmas (id_ano_letivo);
CREATE INDEX IF NOT EXISTS idx_turmas_id_serie ON turmas (id_serie);
CREATE INDEX IF NOT EXISTS idx_turmas_id_salas ON turmas (id_salas);
