CREATE TABLE IF NOT EXISTS `params_turnos` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`sigla` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`horario_inicio` TIME NULL DEFAULT NULL,
	`horario_final` TIME NULL DEFAULT NULL,
	`status` TINYINT(1) NOT NULL DEFAULT '1',
	`text` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`excluido` INT NOT NULL DEFAULT '0',
	`criado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`atualizado_em` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
