CREATE TABLE IF NOT EXISTS usuariosPermissoes (
    id INT NOT NULL AUTO_INCREMENT,
    text VARCHAR(20) NOT NULL,
    idCargo INT (11) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    excluido INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);
