version: '3.8'

services:
  app:
    build: .
    container_name: sistema_educacional
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: sistema_educacional-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_educacional
      # Do not set MYSQL_USER=root. Use only MYSQL_ROOT_PASSWORD for the root user
      # To create a non-root user, set MYSQL_USER and MYSQL_PASSWORD to a different username/password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 5s
      interval: 10s
      retries: 5

volumes:
  mysql_data:
  node_modules: